clone:
  git:
    image: plugins/git
    depth: 1
pipeline:
  build_step:
    image: plugins/docker
    username: ihealth
    password: iHealthStrategy2018
    registry: harbor.ihealthcn.com
    repo: harbor.ihealthcn.com/swift-snail/swift-snail
    mirror: 'https://registry.docker-cn.com'
    tag:
      - '${DRONE_BUILD_NUMBER}'
      - latest
    dockerfile: docker/stg/Dockerfile
    when:
      branch: develop
      event: push
  report-build:
    image: clem109/drone-wechat
    secrets:
      - plugin_corp_secret
      - plugin_corpid
      - plugin_agent_id
    title: '${DRONE_REPO_NAME}'
    description: |
      构建序列: ${DRONE_BUILD_NUMBER}失败。急速 🐌🐌🐌🐌🐌🐌🐌🐌 构建失败，点击卡片查询详细信息。
    msg_url: '${DRONE_BUILD_LINK}'
    btn_txt: 查看详情
    when:
      status:
        - failure
  rancher:
    image: peloton/drone-rancher
    url: 'http://rancher.ihealthcn.com/v2-beta/projects/1a46'
    access_key: FC6450BBAC9464CD0069
    secret_key: 2mbbTGC2rHFV4kghdYfZwDfjmbsR94KwKDhcaWZ5
    service: 301-stg/swift-snail
    docker_image: 'harbor.ihealthcn.com/swift-snail/swift-snail:latest'
    batch_size: 1
    timeout: 600
    confirm: true
    when:
      branch: develop
      event: push
  report-deploy:
    image: clem109/drone-wechat
    secrets:
      - plugin_corp_secret
      - plugin_corpid
      - plugin_agent_id
    title: '${DRONE_REPO_NAME}'
    description: |
      构建序列: ${DRONE_BUILD_NUMBER} 部署成功！ 我们已经帮您自动部署到Rancher，急速 🐌🐌🐌🐌🐌🐌🐌🐌 已经充满能量！
      更新内容: ${DRONE_COMMIT_MESSAGE}
    msg_url: 'http://120.92.88.112:3082/'
    btn_txt: 查看运行状况
    when:
      branch: develop
      status:
        - success
        - failure
